import {
  Users,
  UserPlus,
  UserMinus,
  UserCheck,
  UserCog,
  UsersRound,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Clock,
  Calendar,
  Bell,
  Settings,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Info,
  Layers,
  Home
} from "lucide-react";

export const Icons = {
  users: Users,
  userPlus: UserPlus,
  userMinus: UserMinus,
  userCheck: UserCheck,
  userCog: UserCog,
  group: UsersRound,
  shield: Shield,
  shieldAlert: ShieldAlert,
  shieldCheck: ShieldCheck,
  clock: Clock,
  calendar: Calendar,
  bell: Bell,
  settings: Settings,
  alert: AlertTriangle,
  success: CheckCircle,
  error: XCircle,
  info: Info,
  layers: Layers,
  home: Home,
}; 